import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex *:flex-1">
          <div className=" bg-[#0E0E22]"></div>

          {children}
        </main>
      </body>
    </html>
  );
}
