import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function DashboardLayout({ children }) {
  return (
    <div className="flex h-full">
      <Sidebar />
      <main className="flex-1 h-full overflow-scroll bg-[#EBEDF6]">
        <nav className="bg-white py-4 px-8">
          <div className="hamburger">=</div>
        </nav>
        {children}
      </main>
    </div>
  );
}
