import Sidebar from '@/components/layout/Sidebar';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Dialog } from '@/components/ui/dialog';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const inter = Inter({ subsets: ['latin'] });

export default function DashboardLayout({ children }) {
  return (
    <div className="flex h-full ">
      <Sidebar />
      <main className="flex-1 h-full bg-[#EBEDF6] overflow-y-scroll">
        <Dialog>
          <nav className="bg-white py-4 px-8">
            <div className="hamburger">=</div>
          </nav>
          {children}
        </Dialog>
      </main>
    </div>
  );
}
