import "../globals.css";
import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full">
          <Sidebar />
          <main className="flex-1 h-full overflow-scroll bg-[#EBEDF6]">
            <nav className="bg-white py-4 px-8">
              <div className="hamburger">=</div>
            </nav>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
